# Generated by Django 2.2.4 on 2019-08-15 16:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('path', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=2000)),
                ('location', models.CharField(max_length=250)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(default=0.0)),
                ('bathroom', models.IntegerField(default=0)),
                ('bedroom', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'property',
                'verbose_name_plural': 'properties',
            },
        ),
    ]
