# Generated by Django 2.2.4 on 2019-08-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20190813_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(default='', max_length=20, null=True),
        ),
    ]
